const PLAIN_KEY='hakkim-v09-live-cases';
const VAULT_KEY='hakkim-v10-vault';
const limit=186000;
let sessionKey=null;
let sessionCases=null;
let pendingEvidence=[];
let reminderTimer=null;
const enc=new TextEncoder(),dec=new TextDecoder();

const official={
  retail:{name:'Tüketici Hakem Heyeti',url:'https://www.turkiye.gov.tr/tuketici-sikayeti-uygulamasi'},
  subscription:{name:'BTK Tüketici Şikâyet Sistemi',url:'https://www.turkiye.gov.tr/btk-tuketici-sikayet-bildirim-sistemi-4764'},
  finance:{name:'TBB Bireysel Müşteri Hakem Heyeti',url:'https://www.tbb.org.tr/finansal-tuketici/bireysel-musteri-hakem-heyeti'},
  cargo:{name:'Tüketici Hakem Heyeti',url:'https://www.turkiye.gov.tr/tuketici-sikayeti-uygulamasi'},
  flight:{name:'SHGM Yolcu Hakları',url:'https://kdmerp.shgm.gov.tr/YhkYolcuHaklariYonlendirme/index'},
  other:{name:'Tüketici Hakem Heyeti',url:'https://www.turkiye.gov.tr/tuketici-sikayeti-uygulamasi'}
};
const rules={
  retail:{label:'Ayıplı mal / iade',ev:['Fatura veya sipariş kaydı','Ürün fotoğrafı / video','Satıcıyla yazışmalar']},
  subscription:{label:'Abonelik / GSM / internet',ev:['Abonelik veya sözleşme bilgisi','Faturalar','İptal/itiraz talebi ve işletmeci yanıtı']},
  finance:{label:'Banka / kart',ev:['Ekstre','İşlem dekontu','Bankaya yapılan ilk itiraz kaydı']},
  cargo:{label:'Kargo / teslimat',ev:['Sipariş kaydı','Kargo takip ekranı','Teslim tutanağı veya yazışmalar']},
  flight:{label:'Uçuş / yolcu hakları',ev:['PNR / bilet','Boarding pass','Havayoluna yapılan ilk başvuru kaydı']},
  other:{label:'Diğer tüketici uyuşmazlığı',ev:['Fatura veya sözleşme','Yazışmalar','Olayı destekleyen belgeler']}
};
function classify(t){t=t.toLocaleLowerCase('tr-TR');if(/uçuş|havayolu|pnr|rötar|gecikme.*uç/.test(t))return'flight';if(/kargo|teslim|kurye/.test(t))return'cargo';if(/banka|kart|aidat|ekstre|tahsilat|komisyon/.test(t))return'finance';if(/abonelik|gsm|internet|operatör|taahhüt/.test(t))return'subscription';if(/ürün|iade|ayıplı|bozuk|garanti|satıcı|sipariş/.test(t))return'retail';return'other'}
function route(cat,amt){if(cat==='flight')return'Havayoluna ilk yazılı başvurudan sonra, koşulları karşılıyorsa SHGM yolcu hakları yönlendirmesi değerlendirilebilir.';if(cat==='subscription')return'Telekom/GSM/internet uyuşmazlıklarında işletmeciye ilk başvurudan sonra BTK tüketici kanalı değerlendirilebilir.';if(cat==='finance')return'Bankaya ilk yazılı itirazdan sonra uygun durumda TBB Bireysel Müşteri Hakem Heyeti değerlendirilebilir.';if(Number.isFinite(amt)&&amt>=limit)return'186.000 TL ve üzerindeki tüketici uyuşmazlıkları Tüketici Hakem Heyeti kapsamı dışındadır; uyuşmazlığın niteliğine göre sonraki hukuki yol ayrıca değerlendirilmelidir.';return'2026 yılında 186.000 TL altındaki tüketici uyuşmazlıklarında Tüketici Hakem Heyeti başvurusu değerlendirilebilir.'}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function b64(bytes){let s='';for(const x of bytes)s+=String.fromCharCode(x);return btoa(s)}
function unb64(s){const raw=atob(s),out=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)out[i]=raw.charCodeAt(i);return out}
async function deriveKey(password,salt){const base=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:250000,hash:'SHA-256'},base,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
async function encryptCases(cases,key,salt){const iv=crypto.getRandomValues(new Uint8Array(12));const cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,enc.encode(JSON.stringify(cases)));return{v:1,kdf:'PBKDF2-SHA256',iterations:250000,alg:'AES-GCM',salt:b64(salt),iv:b64(iv),cipher:b64(new Uint8Array(cipher))}}
async function decryptVault(vault,password){const salt=unb64(vault.salt),key=await deriveKey(password,salt);const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(vault.iv)},key,unb64(vault.cipher));return{key,cases:JSON.parse(dec.decode(plain))}}
function vaultExists(){return !!localStorage.getItem(VAULT_KEY)}
function loadPlain(){try{return JSON.parse(localStorage.getItem(PLAIN_KEY))||[]}catch{return[]}}
function load(){if(vaultExists()){return sessionCases||[]}return loadPlain()}
async function persist(cases){if(vaultExists()){if(!sessionKey)throw new Error('Kasa kilitli');const vault=JSON.parse(localStorage.getItem(VAULT_KEY));const encrypted=await encryptCases(cases,sessionKey,unb64(vault.salt));localStorage.setItem(VAULT_KEY,JSON.stringify(encrypted));sessionCases=cases}else{localStorage.setItem(PLAIN_KEY,JSON.stringify(cases))}renderList();scheduleReminders()}
function download(name,data,type='application/json'){const blob=new Blob([data],{type});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),500)}
function exportCase(x){download('hakkim-ai-vaka-'+new Date(x.at).toISOString().slice(0,10)+'.json',JSON.stringify({version:'0.10-local-first',exported_at:new Date().toISOString(),case:x,route:route(x.category,x.amount),evidence:rules[x.category]?.ev||rules.other.ev},null,2))}
function fmtReminder(v){if(!v)return'';const d=new Date(v);return Number.isNaN(d.getTime())?'':d.toLocaleString('tr-TR')}
function isDue(v){return v&&new Date(v).getTime()<=Date.now()}
function renderList(){const locked=vaultExists()&&!sessionKey;const data=load();document.querySelector('#count').textContent=locked?'—':data.length;document.querySelector('#form').classList.toggle('locked',locked);const state=document.querySelector('#vaultState'),detail=document.querySelector('#vaultDetail');if(!vaultExists()){state.textContent='Kasa kapalı';detail.textContent='Vakalar bu tarayıcıda yerel tutuluyor.'}else if(locked){state.textContent='Kasa kilitli';detail.textContent='Vakaları görmek için “Kasayı yönet” ile kilidi aç.'}else{state.textContent='Kasa açık · şifreli';detail.textContent='Vaka listesi AES‑GCM ile cihazda şifreli tutuluyor.'}const list=document.querySelector('#list');if(locked){list.innerHTML='<div style="color:#8096ad;padding:12px 0">Şifreli kasa kilitli.</div>';return}list.innerHTML=data.length?data.map((x,i)=>`<div class="item"><div><b>${esc(x.company||'Firma belirtilmedi')}</b><small>${esc(rules[x.category]?.label||rules.other.label)} · ${x.evidence?.length||0} kanıt özeti</small>${x.reminderAt?`<div class="reminder ${isDue(x.reminderAt)?'due':''}">⏰ ${esc(fmtReminder(x.reminderAt))}${isDue(x.reminderAt)?' · zamanı geldi':''}</div>`:''}</div><div class="right"><strong>${x.amount?Number(x.amount).toLocaleString('tr-TR')+' TL':'Tutar yok'}</strong><small>${new Date(x.at).toLocaleString('tr-TR')}</small><button class="mini" data-open="${i}">Aç</button></div></div>`).join(''):'<div style="color:#8096ad;padding:12px 0">Henüz vaka yok.</div>';list.querySelectorAll('[data-open]').forEach(b=>b.addEventListener('click',()=>show(data[Number(b.dataset.open)])))}
function evidenceHtml(items=[]){if(!items.length)return'<div class="file-status">Bu vakada kanıt dosyası özeti yok.</div>';return'<div class="evidence-box">'+items.map(x=>`<div class="evidence-row"><div><b>${esc(x.name)}</b><br><span>${esc(x.type||'dosya')} · ${Number(x.size||0).toLocaleString('tr-TR')} bayt</span><br><code>SHA‑256 ${esc(x.sha256)}</code></div></div>`).join('')+'</div>'}
function show(x){const r=rules[x.category]||rules.other,o=official[x.category]||official.other,desired=x.desired||'uygun çözümün sağlanması';const draft=`Konu: Tüketici talebi\n\nSayın ${x.company||'ilgili firma'},\n\n${x.desc}\n\nBu olayla ilgili olarak ${desired} talep ediyorum. Talebimin yazılı olarak değerlendirilmesini ve tarafıma yazılı yanıt verilmesini rica ederim.\n\nSaygılarımla.`;document.querySelector('#result').innerHTML=`<span class="pill">${esc(r.label)}</span><h2>${esc(x.company||'Tüketici vakası')}</h2><div class="route"><b>Önerilen rota</b><br>${esc(route(x.category,x.amount))}<br><br><a target="_blank" rel="noopener" href="${o.url}">Resmî kanalı aç → ${esc(o.name)}</a></div>${x.reminderAt?`<div class="reminder ${isDue(x.reminderAt)?'due':''}">⏰ Hatırlatma: ${esc(fmtReminder(x.reminderAt))}${isDue(x.reminderAt)?' · zamanı geldi':''}</div>`:''}<h3>Kanıt kontrol listesi</h3><ul>${r.ev.map(e=>`<li>${esc(e)}</li>`).join('')}</ul><h3>Seçilen kanıt dosyalarının yerel özeti</h3>${evidenceHtml(x.evidence)}<h3>Sıradaki adımlar</h3><ol><li>Kanıtları güvenli bir klasörde sakla.</li><li>Firmaya tarih kaydı bırakacak yazılı talep gönder.</li><li>Yanıta ve uyuşmazlığın türüne göre uygun resmî kanala geç.</li></ol><h3>İlk talep taslağı</h3><div class="draft">${esc(draft)}</div><div class="action-row"><button class="mini" id="copyDraft">Taslağı kopyala</button><button class="mini" id="exportCase">Vakayı JSON indir</button></div>`;document.querySelector('#copyDraft').onclick=async()=>{try{await navigator.clipboard.writeText(draft);document.querySelector('#copyDraft').textContent='Kopyalandı ✓'}catch{}};document.querySelector('#exportCase').onclick=()=>exportCase(x)}
async function hashFile(file){const buf=await file.arrayBuffer();const digest=await crypto.subtle.digest('SHA-256',buf);return{name:file.name,type:file.type||'application/octet-stream',size:file.size,lastModified:file.lastModified,sha256:[...new Uint8Array(digest)].map(b=>b.toString(16).padStart(2,'0')).join('')}}
document.querySelector('#evidenceFiles').addEventListener('change',async e=>{const files=[...e.target.files].slice(0,10);const status=document.querySelector('#fileStatus');if(!files.length){pendingEvidence=[];status.textContent='Dosya seçilmedi.';return}status.textContent='SHA‑256 özetleri hazırlanıyor…';pendingEvidence=[];for(const f of files){pendingEvidence.push(await hashFile(f))}status.textContent=pendingEvidence.length+' dosya özeti hazır. Dosya içeriği sunucuya gönderilmedi.'});
document.querySelector('#form').addEventListener('submit',async e=>{e.preventDefault();if(vaultExists()&&!sessionKey){alert('Önce kasanın kilidini aç.');return}const desc=document.querySelector('#desc').value.trim(),amountRaw=document.querySelector('#amount').value.replace(',','.');const x={id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),company:document.querySelector('#company').value.trim(),amount:amountRaw?Number(amountRaw):null,date:document.querySelector('#date').value,desc,desired:document.querySelector('#desired').value.trim(),reminderAt:document.querySelector('#reminderAt').value||null,evidence:pendingEvidence,category:classify(desc),status:'taslak',at:Date.now()};const arr=load();arr.unshift(x);await persist(arr.slice(0,50));pendingEvidence=[];document.querySelector('#evidenceFiles').value='';document.querySelector('#fileStatus').textContent='Dosya seçilmedi.';show(x)});
document.querySelector('#exportAll').addEventListener('click',()=>{if(vaultExists()&&!sessionKey){alert('Yedek almak için önce kasanın kilidini aç.');return}download('hakkim-ai-v010-yedek.json',JSON.stringify({version:'0.10-local-first',exported_at:new Date().toISOString(),cases:load()},null,2))});
document.querySelector('#importBtn').onclick=()=>document.querySelector('#importFile').click();
document.querySelector('#importFile').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;if(vaultExists()&&!sessionKey){alert('İçe aktarmak için önce kasanın kilidini aç.');return}try{const data=JSON.parse(await file.text());if(!Array.isArray(data.cases))throw new Error('Geçersiz yedek');if(!confirm(data.cases.length+' vaka bu tarayıcıya aktarılsın mı?'))return;const current=load(),seen=new Set(current.map(x=>x.id));const merged=[...current,...data.cases.filter(x=>x&&x.id&&!seen.has(x.id))].slice(0,100);await persist(merged)}catch{alert('Yedek dosyası okunamadı.')}finally{e.target.value=''}});
document.querySelector('#reset').addEventListener('click',()=>{if(!confirm('Bu tarayıcıdaki tüm Hakkım AI vakaları ve şifreli kasa silinsin mi?'))return;localStorage.removeItem(PLAIN_KEY);localStorage.removeItem(VAULT_KEY);sessionKey=null;sessionCases=null;renderList();document.querySelector('#result').innerHTML='<div class="empty"><div class="orb">H</div><h2>Vaka analizi burada oluşacak</h2><p>Kategori, resmî rota, kanıt listesi ve ilk talep taslağı tek ekranda.</p></div>'});
const dialog=document.querySelector('#vaultDialog'),msg=document.querySelector('#vaultMessage');
document.querySelector('#vaultBtn').onclick=()=>{msg.textContent='';document.querySelector('#vaultPassword').value='';dialog.showModal()};
document.querySelector('#enableVault').onclick=async()=>{const password=document.querySelector('#vaultPassword').value;if(password.length<8){msg.textContent='Parola en az 8 karakter olmalı.';return}if(vaultExists()){msg.textContent='Kasa zaten mevcut. Önce kilidi aç veya kasayı kaldır.';return}try{const cases=loadPlain(),salt=crypto.getRandomValues(new Uint8Array(16)),key=await deriveKey(password,salt),vault=await encryptCases(cases,key,salt);localStorage.setItem(VAULT_KEY,JSON.stringify(vault));localStorage.removeItem(PLAIN_KEY);sessionKey=key;sessionCases=cases;msg.textContent='Kasa etkinleştirildi.';renderList()}catch{msg.textContent='Kasa oluşturulamadı.'}};
document.querySelector('#unlockVault').onclick=async()=>{if(!vaultExists()){msg.textContent='Önce kasayı etkinleştir.';return}const password=document.querySelector('#vaultPassword').value;try{const vault=JSON.parse(localStorage.getItem(VAULT_KEY)),out=await decryptVault(vault,password);sessionKey=out.key;sessionCases=out.cases;msg.textContent='Kasa kilidi açıldı.';renderList();scheduleReminders()}catch{msg.textContent='Parola yanlış veya kasa okunamadı.'}};
document.querySelector('#disableVault').onclick=async()=>{if(!vaultExists()){msg.textContent='Aktif kasa yok.';return}if(!sessionKey){msg.textContent='Kasayı kaldırmadan önce kilidi aç.';return}if(!confirm('Şifreleme kaldırılsın ve vakalar yine yalnız bu tarayıcıda düz metin olarak saklansın mı?'))return;localStorage.setItem(PLAIN_KEY,JSON.stringify(sessionCases||[]));localStorage.removeItem(VAULT_KEY);sessionKey=null;sessionCases=null;msg.textContent='Kasa kaldırıldı.';renderList()};
document.querySelector('#notifyBtn').onclick=async()=>{if(!('Notification'in window)){alert('Bu tarayıcı bildirimleri desteklemiyor.');return}const p=await Notification.requestPermission();document.querySelector('#notifyBtn').textContent=p==='granted'?'Bildirim açık ✓':'Bildirim izni yok';scheduleReminders()};
function scheduleReminders(){clearTimeout(reminderTimer);if(vaultExists()&&!sessionKey)return;const upcoming=load().filter(x=>x.reminderAt&&new Date(x.reminderAt).getTime()>Date.now()).sort((a,b)=>new Date(a.reminderAt)-new Date(b.reminderAt))[0];if(!upcoming)return;const delay=Math.min(new Date(upcoming.reminderAt).getTime()-Date.now(),2147483647);reminderTimer=setTimeout(()=>{renderList();if(Notification.permission==='granted')new Notification('Hakkım AI hatırlatma',{body:(upcoming.company||'Vaka')+' için belirlediğin zaman geldi.'});scheduleReminders()},delay)}
renderList();scheduleReminders();
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));