const KEY='hakkim-v09-live-cases';const limit=186000;
const official={
  retail:{name:'Tüketici Hakem Heyeti',url:'https://www.turkiye.gov.tr/tuketici-sikayeti-uygulamasi'},
  subscription:{name:'BTK Tüketici Şikâyet Sistemi',url:'https://www.turkiye.gov.tr/btk-tuketici-sikayet-bildirim-sistemi-4764'},
  finance:{name:'TBB Bireysel Müşteri Hakem Heyeti',url:'https://www.tbb.org.tr/finansal-tuketici/bireysel-musteri-hakem-heyeti'},
  cargo:{name:'Tüketici Hakem Heyeti',url:'https://www.turkiye.gov.tr/tuketici-sikayeti-uygulamasi'},
  flight:{name:'SHGM Yolcu Hakları',url:'https://kdmerp.shgm.gov.tr/YhkYolcuHaklariYonlendirme/index'},
  other:{name:'Tüketici Hakem Heyeti',url:'https://www.turkiye.gov.tr/tuketici-sikayeti-uygulamasi'}
};
const rules={
  retail:{label:'Ayıplı mal / iade',ev:['Fatura veya sipariş kaydı','Ürün fotoğrafı / video','Satıcıyla yazışmalar']},
  subscription:{label:'Abonelik / GSM / internet',ev:['Abonelik veya sözleşme bilgisi','Faturalar','İptal/itiraz talebi ve işletmeci yanıtı']},
  finance:{label:'Banka / kart',ev:['Ekstre','İşlem dekontu','Bankaya yapılan ilk itiraz kaydı']},
  cargo:{label:'Kargo / teslimat',ev:['Sipariş kaydı','Kargo takip ekranı','Teslim tutanağı veya yazışmalar']},
  flight:{label:'Uçuş / yolcu hakları',ev:['PNR / bilet','Boarding pass','Havayoluna yapılan ilk başvuru kaydı']},
  other:{label:'Diğer tüketici uyuşmazlığı',ev:['Fatura veya sözleşme','Yazışmalar','Olayı destekleyen belgeler']}
};
function classify(t){t=t.toLocaleLowerCase('tr-TR');if(/uçuş|havayolu|pnr|rötar|gecikme.*uç/.test(t))return'flight';if(/kargo|teslim|kurye/.test(t))return'cargo';if(/banka|kart|aidat|ekstre|tahsilat|komisyon/.test(t))return'finance';if(/abonelik|gsm|internet|operatör|taahhüt/.test(t))return'subscription';if(/ürün|iade|ayıplı|bozuk|garanti|satıcı|sipariş/.test(t))return'retail';return'other'}
function route(cat,amt){if(cat==='flight')return'Havayoluna ilk yazılı başvurudan sonra, koşulları karşılıyorsa SHGM yolcu hakları yönlendirmesi değerlendirilebilir.';if(cat==='subscription')return'Telekom/GSM/internet uyuşmazlıklarında işletmeciye ilk başvurudan sonra BTK tüketici kanalı değerlendirilebilir.';if(cat==='finance')return'Bankaya ilk yazılı itirazdan sonra uygun durumda TBB Bireysel Müşteri Hakem Heyeti değerlendirilebilir.';if(Number.isFinite(amt)&&amt>=limit)return'186.000 TL ve üzerindeki tüketici uyuşmazlıkları Tüketici Hakem Heyeti kapsamı dışındadır; uyuşmazlığın niteliğine göre sonraki hukuki yol ayrıca değerlendirilmelidir.';return'2026 yılında 186.000 TL altındaki tüketici uyuşmazlıklarında Tüketici Hakem Heyeti başvurusu değerlendirilebilir.'}
function load(){try{return JSON.parse(localStorage.getItem(KEY))||[]}catch{return[]}}
function save(x){localStorage.setItem(KEY,JSON.stringify(x));renderList()}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function download(name,data,type='application/json'){const blob=new Blob([data],{type});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),500)}
function exportCase(x){download('hakkim-ai-vaka-'+new Date(x.at).toISOString().slice(0,10)+'.json',JSON.stringify({version:'0.9-beta',exported_at:new Date().toISOString(),case:x,route:route(x.category,x.amount),evidence:rules[x.category].ev},null,2))}
function renderList(){const data=load();document.querySelector('#count').textContent=data.length;const list=document.querySelector('#list');list.innerHTML=data.length?data.map((x,i)=>`<div class="item"><div><b>${esc(x.company||'Firma belirtilmedi')}</b><small>${esc(rules[x.category]?.label||rules.other.label)}</small></div><div class="right"><strong>${x.amount?Number(x.amount).toLocaleString('tr-TR')+' TL':'Tutar yok'}</strong><small>${new Date(x.at).toLocaleString('tr-TR')}</small><button class="mini" data-open="${i}">Aç</button></div></div>`).join(''):'<div style="color:#8096ad;padding:12px 0">Henüz vaka yok.</div>';list.querySelectorAll('[data-open]').forEach(b=>b.addEventListener('click',()=>show(data[Number(b.dataset.open)])))}
function show(x){const r=rules[x.category]||rules.other,o=official[x.category]||official.other,desired=x.desired||'uygun çözümün sağlanması';const draft=`Konu: Tüketici talebi\n\nSayın ${x.company||'ilgili firma'},\n\n${x.desc}\n\nBu olayla ilgili olarak ${desired} talep ediyorum. Talebimin yazılı olarak değerlendirilmesini ve tarafıma yazılı yanıt verilmesini rica ederim.\n\nSaygılarımla.`;document.querySelector('#result').innerHTML=`<span class="pill">${esc(r.label)}</span><h2>${esc(x.company||'Tüketici vakası')}</h2><div class="route"><b>Önerilen rota</b><br>${esc(route(x.category,x.amount))}<br><br><a target="_blank" rel="noopener" href="${o.url}">Resmî kanalı aç → ${esc(o.name)}</a></div><h3>Kanıt kontrol listesi</h3><ul>${r.ev.map(e=>`<li>${esc(e)}</li>`).join('')}</ul><h3>Sıradaki adımlar</h3><ol><li>Kanıtları tek klasörde topla.</li><li>Firmaya tarih kaydı bırakacak yazılı talep gönder.</li><li>Yanıta ve uyuşmazlığın türüne göre uygun resmî kanala geç.</li></ol><h3>İlk talep taslağı</h3><div class="draft">${esc(draft)}</div><div class="action-row"><button class="mini" id="copyDraft">Taslağı kopyala</button><button class="mini" id="exportCase">Vakayı JSON indir</button></div>`;document.querySelector('#copyDraft').onclick=async()=>{try{await navigator.clipboard.writeText(draft);document.querySelector('#copyDraft').textContent='Kopyalandı ✓'}catch{}};document.querySelector('#exportCase').onclick=()=>exportCase(x)}
document.querySelector('#form').addEventListener('submit',e=>{e.preventDefault();const desc=document.querySelector('#desc').value.trim(),amountRaw=document.querySelector('#amount').value.replace(',','.');const x={id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),company:document.querySelector('#company').value.trim(),amount:amountRaw?Number(amountRaw):null,date:document.querySelector('#date').value,desc,desired:document.querySelector('#desired').value.trim(),category:classify(desc),status:'taslak',at:Date.now()};const arr=load();arr.unshift(x);save(arr.slice(0,50));show(x)});
document.querySelector('#exportAll').addEventListener('click',()=>{const data=load();download('hakkim-ai-vakalar.json',JSON.stringify({version:'0.9-beta',exported_at:new Date().toISOString(),cases:data},null,2))});
document.querySelector('#reset').addEventListener('click',()=>{if(!confirm('Bu tarayıcıdaki tüm Hakkım AI demo vakaları silinsin mi?'))return;localStorage.removeItem(KEY);renderList();document.querySelector('#result').innerHTML='<div class="empty"><div class="orb">H</div><h2>Vaka analizi burada oluşacak</h2><p>Kategori, resmî rota, kanıt listesi ve ilk talep taslağı tek ekranda.</p></div>'});
renderList();
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));