const KEY='hakkim-v09-live-cases';
const limit=186000;
const rules={
  retail:{label:'Ayıplı mal / iade',ev:['Fatura/sipariş kaydı','Ürün fotoğrafı veya video','Satıcıyla yazışmalar']},
  subscription:{label:'Abonelik / GSM',ev:['Abonelik/sözleşme bilgisi','Faturalar','İptal talebi ve operatör yanıtı']},
  finance:{label:'Banka / kart',ev:['Ekstre','İşlem dekontu','Banka itiraz kaydı']},
  cargo:{label:'Kargo / teslimat',ev:['Sipariş kaydı','Kargo takip ekranı','Teslim tutanağı/yazışmalar']},
  flight:{label:'Uçuş',ev:['PNR/bilet','Boarding pass','Havayolu ilk başvuru kaydı']},
  other:{label:'Diğer',ev:['Fatura/sözleşme','Yazışmalar','Olayı destekleyen belgeler']}
};
function classify(t){t=t.toLocaleLowerCase('tr-TR');if(/uçuş|havayolu|pnr|rötar/.test(t))return'flight';if(/kargo|teslim|kurye/.test(t))return'cargo';if(/banka|kart|aidat|ekstre|tahsilat|komisyon/.test(t))return'finance';if(/abonelik|gsm|internet|operatör|taahhüt/.test(t))return'subscription';if(/ürün|iade|ayıplı|bozuk|garanti|satıcı|sipariş/.test(t))return'retail';return'other'}
function route(cat,amt){if(cat==='flight')return'Havayoluna ilk yazılı başvuru → uygun durumda SHGM.';if(cat==='subscription')return'İşletmeci → konuya göre BTK ve/veya tüketici uyuşmazlığı yolu.';if(cat==='finance')return'Bankaya yazılı itiraz → uygun TBB/TKBB / tüketici kanalı.';if(Number.isFinite(amt)&&amt>=limit)return'186.000 TL ve üzeri: THH yerine uyuşmazlığın niteliğine göre arabuluculuk / tüketici mahkemesi değerlendirilir.';return'2026 THH sınırının altındaysa Tüketici Hakem Heyeti yolu değerlendirilebilir.'}
function load(){try{return JSON.parse(localStorage.getItem(KEY))||[]}catch{return[]}}
function save(x){localStorage.setItem(KEY,JSON.stringify(x));renderList()}
function renderList(){const data=load();document.querySelector('#count').textContent=data.length;const list=document.querySelector('#list');list.innerHTML=data.length?data.map(x=>`<div class="item"><div><b>${esc(x.company||'Firma belirtilmedi')}</b><small>${esc(rules[x.category].label)}</small></div><div class="right"><strong>${x.amount?x.amount.toLocaleString('tr-TR')+' TL':'Tutar yok'}</strong><small>${new Date(x.at).toLocaleString('tr-TR')}</small></div></div>`).join(''):'<div style="color:#8096ad;padding:12px 0">Henüz demo vaka yok.</div>'}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function show(x){const r=rules[x.category],desired=x.desired||'uygun çözümün sağlanması';const draft=`Konu: Tüketici talebi\n\nSayın ${x.company||'ilgili firma'},\n\n${x.desc}\n\nBu olayla ilgili olarak ${desired} talep ediyorum. Talebimin yazılı olarak değerlendirilmesini rica ederim.\n\nSaygılarımla.`;document.querySelector('#result').innerHTML=`<span class="pill">${esc(r.label)}</span><h2>${esc(x.company||'Tüketici vakası')}</h2><div class="route"><b>Önerilen rota</b><br>${esc(route(x.category,x.amount))}</div><h3>Kanıt kontrol listesi</h3><ul>${r.ev.map(e=>`<li>${esc(e)}</li>`).join('')}</ul><h3>Sıradaki adımlar</h3><ol><li>Kanıtları tek dosyada topla.</li><li>Firmaya tarih kaydı bırakacak yazılı talep gönder.</li><li>Yanıta göre önerilen resmi rotaya geç.</li></ol><h3>İlk talep taslağı</h3><div class="draft">${esc(draft)}</div>`}
document.querySelector('#form').addEventListener('submit',e=>{e.preventDefault();const desc=document.querySelector('#desc').value.trim(),amountRaw=document.querySelector('#amount').value.replace(',','.');const x={company:document.querySelector('#company').value.trim(),amount:amountRaw?Number(amountRaw):null,date:document.querySelector('#date').value,desc,desired:document.querySelector('#desired').value.trim(),category:classify(desc),at:Date.now()};const arr=load();arr.unshift(x);save(arr.slice(0,20));show(x)});
document.querySelector('#reset').addEventListener('click',()=>{localStorage.removeItem(KEY);renderList();document.querySelector('#result').innerHTML='<div class="empty"><div class="orb">H</div><h2>Vaka analizi burada oluşacak</h2><p>Kategori, resmi rota, kanıt listesi ve ilk talep taslağı tek ekranda.</p></div>'});renderList();
